browser=chrome
baseURL=https://www.demoblaze.com
timeout=10
headless=true

baseUsername=testuser
password=Test@123

validUsername=mohan1698
validPassword=mohan

invalidUsername=wrongUser
invalidPassword=wrongPass